image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      yarn install
      npm install -g mocha 
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends pkg-config build-essential libudev-dev
      cargo install --git https://github.com/project-serum/anchor --tag v0.18.2 anchor-cli --locked
    command: |
      solana-keygen new --no-bip39-passphrase -o keypair.json
      solana config set --keypair keypair.json
      solana config set --url localhost
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: false
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
ports:
  - port: 1024
    onOpen: ignore
  - port: 8899
    onOpen: ignore
  - port: 8900
    onOpen: ignore
  - port: 9900
    onOpen: ignore
vscode:
  extensions:
    - beardedbear.beardedtheme
    - ms-azuretools.vscode-docker
    - usernamehw.errorlens
    - dbaeumer.vscode-eslint
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - yzhang.markdown-all-in-one
    - pkief.material-icon-theme
    - csstools.postcss
    - esbenp.prettier-vscode
    - rust-lang.rust
    - voorjaar.windicss-intellisense
