[programs.devnet]
myepicproject = "2Sj1RrnyV1zU1YgXVP5K9mdEbDuGe8nEcukePMkab1vt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "keypair.json"

[scripts]
test = "node tests/myepicproject.js"
